openapi: 3.1.0
info:
  title: Core System API
  version: 1.0.0
tags: []
paths: {}
components:
  schemas:
    Versions:
      type: string
      enum:
        - 1.0.0
servers:
  - url: https://example.com
    description: Single server endpoint
    variables: {}
